Install `peerme` as executable & moved the entry_point into the module
cooperlees/peerme pull request #17
Opened 2016-10-23 20:53 UTC by andir

2016-10-24 05:59 UTC, cooperlees requested changes
Let's do 2 things:
- rename to main.py
- test templating still works, I'm worried about the relative lame pathing we've used (generate.py)

2016-10-24 23:23 UTC, andir commented
Your are right about the name.. just didn't come up with a good name at the time. i'll get on those changes in the morning :-)

2016-10-25 10:12 UTC, andir commented
I moved the templates into the `peerme` packaged and added them to the `MANIFEST.in` so they are being included in the installed package. Also the `peerme.commands` package was missing.

Running the `peerme` examples from /tmp/ with peerme in my path resulted in the correct output. I think this works as expected.

2016-10-25 10:19 UTC, flokli commented on setup.py
> +# since we've disutils support we can't use setuptools.find_packages for this
typo at 'disutils'

2016-10-25 15:04 UTC, cooperlees approved these changes
lgtm

2016-10-25 15:04 UTC, merged